server_host = "10.1.5.2"
server_port = 80

[attack]
gateway_ext_ip = "10.1.1.3"
gateway_int_ip = "10.1.5.3"
spoof_blacklist = [
    "10.1.1.2",  # router
    "10.1.2.3",  # router
    "10.1.3.3",  # router
    "10.1.4.3",  # router
    "10.1.4.2",  # legitimate client
]
clients = [
    "10.1.2.2", # client1
    "10.1.3.2", # client2
    "10.1.4.2", # client3
]

[[our_users]]  # his new job
user = "gigi"
password = "dimaiodimaio"

[[our_users]]
user = "peppa"
password = "pigporcod"

[[default_users]]
user = "jelena"
password = "abcdef"

[[default_users]]
user = "john"
password = "abcdef"

[[default_users]]
user = "kate"
password = "abcdef"
